### ISSUE TITLE
Rules with an empty head can be entered into the rule editor

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/swrltab-plugin#12]
Actually, it accepts a single atom ```A(?x)```.  Should this be allowed?

**Comment by martinjoconnor** [comment]
I think this is correct (though is effectively a null operation).

https://www.w3.org/Submission/SWRL/, Section 2.1:

"A rule axiom consists of an antecedent (body) and a consequent (head), each of which consists of a (posibly empty) set of atoms. "
