### ISSUE TITLE
Incorrect renderring of the '^' symbol on Windows

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#14]
The symbol corresponding to the '^' character is not rendered properly on Windows:
![swrltab-incorrect symbols](https://cloud.githubusercontent.com/assets/2441046/13103593/56e617ec-d50c-11e5-8743-e65d5bf03526.png)

**Comment by matthewhorridge** [comment]
Consider using commas to separate atoms instead.  These are easier to type, render correctly on different platforms and the rest of Protege uses commas for rule rendering.

**Comment by martinjoconnor** [comment]
Have been using these hats for a decade and really dislike the commas - they look too formal. I would also have to change craploads of documentation.

This Unicode symbol is pretty standard (\u2227). Is the JVM packaged with the current distribution? From the little searching I have done it appears that Unicode rendering issues on Windows are related to font configurations: 

http://www.thecodingforums.com/threads/problem-with-java-displaying-unicode-under-ms-windows.948381/

**Comment by martinjoconnor** [comment]
No longer use Unicode characters as of 1.0.10.
