### ISSUE TITLE
Error message shown while updating to latest version SWRLTab

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#16]
After installing the latest version of SWRLTab (1.0.0.beta-13), the following error message is shown:
"Some errors occurred whilst installing downloaded plugins". Everything seem to work fine, though.
The problem may be in the Protege code: https://github.com/protegeproject/protege

This was also reported by others on the mailing list:
http://protege-project.136.n4.nabble.com/errors-of-SQWRL-td4664606.html#a4664613

**Comment by csnyulas** [comment]
Here is a screen shot of the error message:
![screenshot_protege_plugin_installer_error](https://cloud.githubusercontent.com/assets/2441046/13475943/527ecfd6-e07a-11e5-8f85-919f960453c1.png)

I just observed that clicking on the "View log" button does not bring up the log view.

BTW, this happens when updating to SWRLTab  version 1.0.0.beta-15 too.

**Comment by matthewhorridge** [comment]
This is a core protege message (it's already been fixed).
