### ISSUE TITLE
After running the rule engine all inferred axioms are asserted in the ontology

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#17]
After running the (DROOLS) rule engine in SWRLTab, I get a lot of trivial inferences asserted in my ontology, such as owl:Nothing is subclass of all the classes (including owl:Thing), and every class is subclass of owl:Thing (including owl:Nothing). Moreover, every class will be stated as being subclass of itself (including owl:Thing and owl:Nothing), which makes all classes to be shown as defined classes (i.e. with the icon showing the equivalent symbol).

![protege_swrltab_inference](https://cloud.githubusercontent.com/assets/2441046/13424709/3fe13d74-df57-11e5-8f71-7a89be3b1f03.png)

This behaviour is not only very confusing, but if the ontology was not saved prior to running the rule(s), once the rule engine is run, it is not possible to save the ontology without the inferred statements, as it was its state just before running the rules.

**Comment by matthewhorridge** [comment]
Why do inferred axioms end up as asserted axioms?  Is this something that the user requests or does it happen automatically?

**Comment by martinjoconnor** [comment]
When the user selects to transfer the asserted axioms back to OWL from the SWRLTab they currently simply get added to the active ontology as asserted axioms. I wrote this part of the code a while ago and forgot about it. How should I handle this? I vaguely recall some discussions about this but have forgotten the details.

(Note that this behaviour is not the case with the net-yet-ready OWL 2 RL reasoner plugin, which conforms to the standard reasoner interface.)

**Comment by matthewhorridge** [comment]
Is there really a need for this transfer?  What purpose does it serve?

**Comment by csnyulas** [comment]
The only way to visually inspect, in context, the result of running the rules, is to click on the third button at the bottom of SWRLTab to "Translate asserted rule engine knowledge to OWL knowledge". If we don't do this, our only information on the effect of the rules is coming from the different statements presented in SWRLTab, which is not that easy to interpret.

It would be desirable that the rule engine's knowledge is transferred as inferred knowledge, not as asserted one.

**Comment by matthewhorridge** [comment]
>  The only way to visually inspect, in context, the result of running the rules, is to click on the third button at the bottom of SWRLTab to "Translate asserted rule engine knowledge to OWL knowledge". If we don't do this, our only information on the effect of the rules is coming from the different statements presented in SWRLTab, which is not that easy to interpret.

> It would be desirable that the rule engine's knowledge is transferred as inferred knowledge, not as asserted one.

Ah right.  This problem will disappear as @martinjoconnor is going to turn the SWRL Tab Reasoner into a proper reasoner plugin.  Once this is done, inferences will be presented as they are when using any other reasoner (i.e. inline with a yellow background).  Once this has been implemented my suggestion is to remove this transfer functionality.

**Comment by martinjoconnor** [comment]
I have filtered a lot of 'redundant' axioms (related to owl:Thing and owl:Nothing and top and bottom data and object properties, and intermediate subclass and sub property axioms in hierarchies) so at least now the functionality should be usable. 

The users will still see a crapload of inferred axioms but it will not mess up their class and property hierarchies.

**Comment by hanaamer93** [comment]
I have the same problem now It would be desirable for my application that the rule engine's knowledge is transferred as inferred knowledge, not as asserted one but I am using SWRLJess not Drools because my SWRL rules include sqwrl built in functions which as I understood is not supported by Drools .So How should I improve this point ?Has the SWRLTab Reasoner been turned to a proper plugin as you've mentioned or not yet ?

**Comment by martinjoconnor** [comment]
The version of the SWRLTab plugin in this repo only supports Drools - and provides all functionality of the earlier Protege 3-, Jess-based plugin, including SQWRL. 

The OWL 2 RL-based reasoner used by the SWRLTab plugin has not be made available as a reasoner plugin for Protege itself. Unfortunately, there are no current plans to perform this work.

**Comment by hanaamer93** [comment]
Does this includes Protege 5.1 ? As I've read that it only supports SWRL-Drools but not Jess ? And what is the version of this plugin please ?
So what do you propose shall I use Jess Rules or any type of production rule systems to have a dynamic classification ( I mean to support a non-monotonic reasoning , where the fact could change )?

**Comment by martinjoconnor** [comment]
The OWLAPI-based version of the SWRLTab works with Protege 5.0+. The latest version of the plugin is 2.0.0.

Drools is used in place of Jess in the SWRLAPI-based version. Note, however, that Jess and Drools are implementation details - they are used only for implementing an OWL 2 RL-based reasoner. Their APIs were not exposed either in the initial version of the SWRLAPI or in the current version. 

If you want to to be able to non-montonically update an OWL knowledge base in the way you desire you will have to use direct API-based manipulation of OWL entities via a production rule system or the equivalent. OWL and SWRL do not support this type of inference and the SWRLAPI adheres to the formal semantics of both languages.

https://github.com/protegeproject/swrlapi/wiki/SWRLLanguageFAQ#Does_SWRL_support_Nonmonotonic_Inference

**Comment by hanaamer93** [comment]
"If you want to to be able to non-montonically update an OWL knowledge base in the way you desire you will have to use direct API-based manipulation of OWL entities via a production rule system or the equivalent"
I am sorry can you please elaborate this in details I don't get what should I do and with example ?
What I am trying to do now is to use Jess and Jess Tab in Protege to map the ontology concepts , and then define the rules I want as Jess supports non monotonic reasoning where you can assert , modify and remove facts and flexible to write my functions using loops/if conditions . I actually wanted to able able to do it with SWRL but it seems that my target ( adaptive classification of instances ) can not be supported with OWL+SWRL.
Thank you so much .

**Comment by martinjoconnor** [comment]
Protege 3 had the JessTab (which was completely unrelated to the SWRLTab and its use of Jess for implementing a SWRL rule engine) that allowed direct manipulation of knowledge base entities. I do not think there is a direct equivalent in Protege 5.

I would email the Protege mailing list to ask about this.

http://protege.stanford.edu/support.php

**Comment by hanaamer93** [comment]
Yes,this is what I am doing now , I am learning JESS and how to manipulate a knowledge base using Jess Tab. Ok , will contact them Thanks .

**Comment by hanaamer93** [comment]
Hi Martin , I have a question in SWRLJess , if I mapped more than one instance of a class , the Jess engine will classify only 1 instance at a time correctly , I mean you have to send instance per instance to the engine else it won't classify it correctly.Is this a feature of Jess . And is there a way to force Jess engine to consider more than 1 message at a time ?

**Comment by martinjoconnor** [comment]
I am not sure what SWRLJess is. Are you referring to the Protege JessTab (which is completely unrelated to SWRL)? Note that the SWRLAPI in the repo does not use Jess. Jess was used in the old Protege-3 SWRLAPI, which is no longer supported.

**Comment by hanaamer93** [comment]
I am referring to SWRL tab and it use for jess support and also Jess Tab with the jess rules  , I am using Protege 3.4.1 already. 
I would share with you a link with my question and the problem I am facing . Despite the fact that the link includes the problem with the JessTab only but my rules in SWRL Tab with Jess support have 2 problems the fact assertions which we talked about earlier in the post and we've reached that I used  Jess Rules the other problem is the same as that in this link , If I entered 2 instances of a class and mapped them to the engine ( pressed SWRL+OWL button) only 1 instance is classified correctly while the result is added tthe same for the other  message .
https://stackoverflow.com/questions/44387308/jess-considers-only-the-last-mapped-instance/44410570?noredirect=1#

So my question is that a feature of Jess engine itself ?

The other question  as I told you I have implemented these rules in swrl busing SWRL+Jess Tab in Protege and the rules worked fine the problem was the facts were asserted in the ontology and I want them to be modified not asserted so that's why I used Jess Rules , do you think I am on the write track or I should use Sweet Rules to translate the SWRL rules + ontology classes and indiv. for example better ?

**Comment by martinjoconnor** [comment]
I would post these questions to the Protege mailing list.

http://protege.stanford.edu/support.php

**Comment by runumi** [comment]
How to filter trivial rules from Drools in Protege

**Comment by martinjoconnor** [comment]
You mean filter trivial inferred axioms? 

It is not possible with the current implementation.

I would take a look at [Protege](https://protege.stanford.edu/), which has several reasoners integrated that support more intelligent visualization of inferred axioms.
