### ISSUE TITLE
Plugin Update file Id does not match the symbolic id of the plugin

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/swrltab-plugin#19]
The symbolic id of the SWRL plugin is ```swrltab-plugin```.  The update file at ```https://github.com/protegeproject/swrltab-plugin/blob/master/update-info/protege-5/update.properties``` specifies the id as ```swrlplugin```.  This mismatch causes Protege to think that the SWRL tab is always a newly available plugin.

**Comment by martinjoconnor** [comment]
Will fix and get a new release out later today.

**Comment by martinjoconnor** [comment]
New plugin release (1.0.0-beta-18) now updates without warning.

Thanks.
