### ISSUE TITLE
Query selection in SQWRLTab is not working properly

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#22]
The selection of the SQWRL query to be executed next time the "Run" button is pressed in the SQWRLTab is not working properly. As of version 1.0.0.beta-18, it seems that opening an ontology that contains SQWRL queries will have all rules enabled (i.e. with its checkbox checked), but when I run the queries only one is executed, namely the last one that I have selected, totally ignoring which of the queries have their checkboxes checked and which one do not.

**Comment by martinjoconnor** [comment]
I will look at hiding the checkboxes in the SQWRL tab. 

(It has probably behaved like this since 2009 - thought I agree it makes no sense to show the check boxes.)

**Comment by martinjoconnor** [comment]
Checkboxes gone as of 1.0.10.
