### ISSUE TITLE
sqwrl:makeSet and sqwrl:size example gives an incorrect answer

### ISSUE THREAD

**Issue by johnmharris** [protegeproject/swrltab-plugin#28]
Using Protege 5.0.0-beta-24

Symptom: Using sqwrl:size on a set of all instances returns 1, though there are many instances.
Use the example query from http://protege.cim3.net/cgi-bin/wiki.pl?CollectionsSQWRL

Steps to reproduce:
* Create a new ontology.
* Create a class e.g. MyClass.
* Create a couple of instances of MyClass.
* Open the SQWRLTab and create a new rule: MyClass(?c) ^ sqwrl:makeSet(?d, ?c) ^ sqwrl:size(?z, ?d) -> sqwrl:select(?z)
* Run the rule- the answer is 1, when it should be the number of instances.

Frustratingly this has operated correctly a couple of times, but saving and re-opening the ontology reverts the query answer to 1 again.

**Comment by johnmharris** [comment]
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_66-b17  Memory: 466M 
Language: en, Country: GB 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.16.0-4-686-pae) 
Processor: x86

**Comment by johnmharris** [comment]
[swrltab-plugin-issue28.owl.txt](https://github.com/protegeproject/swrltab-plugin/files/179348/swrltab-plugin-issue28.owl.txt)

**Comment by martinjoconnor** [comment]
I can reproduce this. Will take a look at it tomorrow.

**Comment by martinjoconnor** [comment]
There is a new 1.0.0-beta-30 available with the fix that can be automatically updated from within Protege.

**Comment by johnmharris** [comment]
Confirmed that this fix works. Thanks for your swift response.
