### ISSUE TITLE
Once SWRLTab throws an exception, fixing the rules does not seem to have any effect

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#30]
If you try to run the rules in this ontology, SWRLTab will complain about the use of `xsd:integer` in the rule/SWRL built-in:
[SWRL_test.owl.zip](https://github.com/protegeproject/swrltab-plugin/files/245986/SWRL_test.owl.zip)

After we remove all references to `xsd:integer` from the rule, and even the property value assertion, if we re-run the rules in SWRLTab, it will still be throwing  the same exceptions regarding `xsd:integer`. It seems like the rule engine is not properly reset.

**Comment by martinjoconnor** [comment]
The 2.0.0 release fixes this issue.
