### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by fedeMarra** [protegeproject/swrltab-plugin#31]
Hi,
I downloaded Protégé Desktop Version 5.0.0 Build beta-21, but the swrl-plugin preinstalled didn't work. So I downloaded the later version (1.0.1) and I followed the building from source step, but It presents the same problem. When the program start in the log it is written:
```
Error starting file:/home/federica/Protege-5.0.0-beta-21/plugins/swrltab-plugin-1.0.10.jar 
org.osgi.framework.BundleException: Unresolved constraint in bundle swrltab-plugin [24]: Unable to resolve 24.0: missing requirement [24.0] osgi.wiring.package; (&(osgi.wiring.package=org.semanticweb.owlapi.apibinding)(version>=4.2.5)(!(version>=5.0.0)))
```
I use Ubuntu 14.04 and for Protegè I use Java 8 Oracle. I tried to start the program both with Protegè internal jre both system jre, changing the path in the run.sh file.

I can not understand what is the problem and why there is this error.

**Comment by martinjoconnor** [comment]
You should be using the latest 1.0.0 release of Protege (post RC1 and RC2). It comes pre-packed with the 1.0.3 version of the plugin. You should immediately upgrade to the latest 1.0.10 release (via File->Check for Plugins).

**Comment by fedeMarra** [comment]
I finally resolved!! I didn't know that the plugin doesn't run with Beta release.
Thank you very much @martinjoconnor !
