### ISSUE TITLE
makeBag and makeSet both make a Set

### ISSUE THREAD

**Issue by grandrew** [protegeproject/swrltab-plugin#32]
# Control

`hasMeasure(?ResourceX, ?ProvidedX) ^ isUsedBy(?ResourceX, ?ApplicationX) ^ hasMeasure(?ApplicationX, ?RequiredX) ^ tbox:cd(?cls) ^ abox:caa(?cls, ?ProvidedX) ^ abox:caa(?cls, ?RequiredX) ^ tbox:sca(?cls, ComputeMeasures) ^ hasQuantityValue(?ProvidedX, ?PV) ^ hasQuantityValue(?RequiredX, ?RV) -> sqwrl:select(?ResourceX, ?ProvidedX, ?cls, ?RV)` 

returns

![screenshot 2016-12-21 at 11 59 27](https://cloud.githubusercontent.com/assets/243218/21383077/f29e4be0-c774-11e6-8827-ace4afd40b4a.png)

notice the two elements with `8.0^^double`

# MakeSet experiment

then with `makeSet` returns all but one element with same value (as expected in this case where two elements have same `8.0^^double` value:

`hasMeasure(?ResourceX, ?ProvidedX) ^ isUsedBy(?ResourceX, ?ApplicationX) ^ hasMeasure(?ApplicationX, ?RequiredX) ^ tbox:cd(?cls) ^ abox:caa(?cls, ?ProvidedX) ^ abox:caa(?cls, ?RequiredX) ^ tbox:sca(?cls, ComputeMeasures) ^ hasQuantityValue(?ProvidedX, ?PV) ^ hasQuantityValue(?RequiredX, ?RV) ˚ sqwrl:makeSet(?b, ?RV) -> sqwrl:select(?ResourceX, ?ProvidedX, ?cls, ?RV)`

->

![screenshot 2016-12-21 at 11 59 56](https://cloud.githubusercontent.com/assets/243218/21383087/0249c2d6-c775-11e6-9f46-308cfabb6617.png)

# MakeBag experiment

Changed `makeSet` to `makeBag` to actually include the duplicate value in the result:

`hasMeasure(?ResourceX, ?ProvidedX) ^ isUsedBy(?ResourceX, ?ApplicationX) ^ hasMeasure(?ApplicationX, ?RequiredX) ^ tbox:cd(?cls) ^ abox:caa(?cls, ?ProvidedX) ^ abox:caa(?cls, ?RequiredX) ^ tbox:sca(?cls, ComputeMeasures) ^ hasQuantityValue(?ProvidedX, ?PV) ^ hasQuantityValue(?RequiredX, ?RV) ˚ sqwrl:makeBag(?b, ?RV) -> sqwrl:select(?ResourceX, ?ProvidedX, ?cls, ?RV)`

->

yields the same result as with makeSet, meaning that the result is a set and is ignoring duplicate values:

![screenshot 2016-12-21 at 12 01 38](https://cloud.githubusercontent.com/assets/243218/21383134/3db65852-c775-11e6-961e-c75ecb2ef91e.png)

**Comment by martinjoconnor** [comment]
Your queries are not looking at the actual elements of the sets or bags. You need to used the <tt>sqwrl:element</tt> built-in to pull the elements from a set or bag - and then list those elements.

See: https://github.com/protegeproject/swrlapi/wiki/SQWRLCollections#retrieving-all-elements-from-a-collection
