### ISSUE TITLE
'Invalid OWL individual name' status error when rdfs:label is set for an individual

### ISSUE THREAD

**Issue by agleoni** [protegeproject/swrltab-plugin#35]
Hi,

I'm using Protege-5.2.0 with SWRLTab Protege 5.0+ Plugin (version 1.0.3) and I'm trying to write a rule in which I'm directly using individuals that have an rdfs:label set.

In my ontology I have a class TripLength with ShortTrip and LongTrip as individuals to which are respectively associated the rdfs:labels 'Short trip' and 'Long trip'. 

Without labels the following rule has Status: Ok and the reasoner infers the right property
```
Person(?p) ^ preferredTripLength(?p, LongTrip) -> profiledTypology(?p, Touring)
```
Instead, when a label is set for the individual LongTrip, writing the same rule causes the following error: _Invalid OWL individual name 'LongTrip'_.
Moreover, if this rule is added before setting the labels, it continues to work properly.

The content of the labels is used in my application to display a user-friendly name. 
How should I proceed?

Thanks in advance!

**Comment by martinjoconnor** [comment]
The current SWRLTab release is 2.0.6: https://github.com/protegeproject/swrltab-plugin/releases

The SWRLAPI parser supports only the prefixed name of OWL entities, not labels.

So only something like ```Person``` or ```aprefix:Person``` will work, where ```Person``` is the underlying entity name.
