### ISSUE TITLE
Some problems with writing rules in SWRLTab (protege 5.2.0)

### ISSUE THREAD

**Issue by ying6991** [protegeproject/swrltab-plugin#36]
The symbol " -> " in  SWRL rule is how to knock . But when I click on the button "OK",  symbol " -> " will auto-display, and the rules with a prefix "autogen0:" display as well. For example, when I enter the Room(?r) (I have defined "Room" class) and  click on the button "OK", it will show "autogen0:Room(?r) -> " . 
(1) How do I get the symbol " -> "to appear? and
(2) How to remove the prefix "autogen0:" .
Thanks a lot, 
Ying
![1](https://user-images.githubusercontent.com/26991546/38993199-8d4f30a0-4415-11e8-9487-a0850cdde505.jpg)

![2](https://user-images.githubusercontent.com/26991546/38993600-ab84fa36-4416-11e8-933a-37f8aa447f2e.jpg)

**Comment by martinjoconnor** [comment]
I would use the latest 2.0.6 release of the SWRLTab plugin. A previous
release had a bug relating to generating unnecessary prefixes.

I would also start with a new ontology.

Martin
