### ISSUE TITLE
Building Issue, could not find artifiact

### ISSUE THREAD

**Issue by skyspy2000** [protegeproject/swrltab-plugin#4]
Hi,

We have an issue compiling the SWRtab-plugin, which I checked out yesterday.
Running "mvn clean package" runs into following error:

[ERROR] Failed to execute goal on project swrltab-plugin: Could not resolve dependencies for project org.swrltab:swrltab-plugin:bundle:1.0.5: The following artifacts could not be resolved: org.swrlapi:swrlapi:jar:1.0.5, org.swrlapi:swrlapi-drools-engine:jar:1.0.5: Could not find artifact org.swrlapi:swrlapi:jar:1.0.5 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

Is this a missing artifact on the remote repository?

I hope you can help us with this issue.

best regards
skyspy2000

**Comment by dartheliber** [comment]
Same problem for me

**Comment by jibe-b** [comment]
I get the same problem + searching "swrlapi" on http://repo.maven.org returns nothing.

Does it mean the files are no longer available?

I sent a message to the protege-dev mailinglist too:
http://protege-project.136.n4.nabble.com/SWRL-plugin-P5-td4662240.html

Best regards

**Comment by zippyrate** [comment]
This plugin has not yet been released so none of the artifacts are on Maven central.

The release was delayed to coincide with the next beta release of Protege 5.0 because an updated OWLAPI with SWRL-related bug fixes is required. 

I have updated the README to reflect this release information.

**Comment by mmasroorali** [comment]
I was getting the same error and a search landed me here.

Any tentative date for the release? I seem to badly need it. Thanks.
