### ISSUE TITLE
Exception running rule engine: Prefix not registered for prefix name: _:

### ISSUE THREAD

**Issue by giserxx** [protegeproject/swrltab-plugin#41]
Hi,
When I run the rules, I get this error:
`Exception running rule engine: Prefix not registered for prefix name: _:`

My software environment:
[windows 11]
[protege==5.5]
[swrltab-plugin==2.0.11]

**Comment by IvyWEN331** [comment]
Hi~ i

I have encountered the same problem with you. how you resolve this? thank you

**Comment by martinjoconnor** [comment]
Can you post the ontology here. (You will need to add a .txt extension after .owl because GitHub does not support .owl extensions.)
