### ISSUE TITLE
SWRLTab not available under Window > Tabs in Protege 5.6.1 after most recent update (2.1.2)

### ISSUE THREAD

**Issue by mattolds** [protegeproject/swrltab-plugin#42]
I'm not sure this is where to post this, but more than one of us are having this issue. If you update the SWRLTab plug-in to version 2.1.2, you will lose it from the list of available Tabs. If you don't, you can still use the version that comes bundled with Protege, found under Window > Tabs. 

The updated plug-in still shows up in your list of plugins under Preferences > Plugins and under Help > About, and the .jar file is in the plugins folder, but I can't find how to display it. There's a visually identical version of it under ROWLTab. I'm betting there's just something I don't know about it. If so, I apologize for raising the issue.

**Comment by martinjoconnor** [comment]
Have you tried Protege 5.6.2? It has just been released.

I will try to test with 5.6.1 in the next few days.

**Comment by mattolds** [comment]
Good call. It has been restored to its rightful place in 5.6.2. Thank you! (I don't know the rules for closing an issue, so I'll leave it for you to close.)
