### ISSUE TITLE
SWRL TAB no appearing in window-> tab 

### ISSUE THREAD

**Issue by alexsotocx** [protegeproject/swrltab-plugin#5]
Hello

I compiled the swrltab-plugin-1.0.0.jar using maven and it was successfully builded. After that i copied and pasted in the protege/plugins (Protege-5.0.0-beta-17) and executed the protege script and the plugin was loaded.
![screenshot 2015-10-15 09 25 53](https://cloud.githubusercontent.com/assets/6225534/10516639/df740f42-731e-11e5-8623-966185cb2bab.png)

The protege ran normally but the tab doesn't appear on the UI or in the window -> tabs.
![screenshot 2015-10-15 09 27 46](https://cloud.githubusercontent.com/assets/6225534/10516683/1519d2e4-731f-11e5-9242-61481b50247a.png)

I hope you can help me out

EDIT:
I used the last version of SWRLAPI(https://github.com/protegeproject/swrlapi) and SWRL-DROOLS(https://github.com/protegeproject/swrlapi-drools-engine)

**Comment by martinjoconnor** [comment]
See the following in the README:

*The SWRLTab Plugin has not yet been released. This plugin and related libraries are built using the latest 4.0.2 version of the OWLAPI and the current Protégé 5.0.0 Beta 17 has not yet been updated to use this version. The upcoming Beta 18 release of Protégé will use the latest OWLAPI version. The SWRLTab plugin will be released at the same time.*

Meanwhile you can use the standalone version of the SWRLTab: https://github.com/protegeproject/swrltab

FYI, there is also a build project that will build all SWRLAPI-related components:

https://github.com/protegeproject/swrltab-project
