### ISSUE TITLE
Protégé can't find jar file

### ISSUE THREAD

**Issue by martaac** [protegeproject/swrltab-plugin#7]
When checking for plugins updates Protégé finds version 9 of SWRLTAB, but when installing it can't find the file:
https://github.com/protegeproject/swrltab-plugin/releases/download/swrltab-plugin-1.0.0-beta-9/swrltab-plugin-1.0.0-beta-9.jar

Thanks in advance!

**Comment by martinjoconnor** [comment]
Fixed. Thanks for the report.

**Comment by martaac** [comment]
Thank you !
Marta

Inviato da iPhone
